// Advertising & web analytics specs.

module.exports = [
  {
    name: 'source-facebook-ads',
    displayName: 'Facebook Ads',
    description: 'Campaigns, ad sets, ads and insights from Meta Marketing API.',
    catalogSlug: 'facebook-ads', category: 'Applications', icon: 'facebook',
    baseUrl: 'https://graph.facebook.com/v21.0',
    auth: { type: 'query', param: 'access_token' },
    config: [
      { key: 'accessToken', title: 'System user access token', secret: true, required: true },
      { key: 'adAccountId', title: 'Ad account ID', required: true, help: 'act_1234567890 or the numeric ID' },
    ],
    check: { path: '/me' },
    _act: null,
    resources: [
      { name: 'campaigns', path: '/act_{adAccountId}/campaigns', params: { fields: 'id,name,status,objective,created_time,updated_time,daily_budget,lifetime_budget,buying_type' }, recordsPath: 'data', primaryKey: 'id', cursorField: 'updated_time', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'adsets', path: '/act_{adAccountId}/adsets', params: { fields: 'id,name,status,campaign_id,daily_budget,created_time,updated_time,targeting' }, recordsPath: 'data', primaryKey: 'id', cursorField: 'updated_time', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'ads', path: '/act_{adAccountId}/ads', params: { fields: 'id,name,status,adset_id,creative{id,name},created_time,updated_time' }, recordsPath: 'data', primaryKey: 'id', cursorField: 'updated_time', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'adcreatives', path: '/act_{adAccountId}/adcreatives', params: { fields: 'id,name,status,thumbnail_url,object_type' }, recordsPath: 'data', primaryKey: 'id', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'insights', path: '/act_{adAccountId}/insights', params: { fields: 'campaign_id,campaign_name,impressions,clicks,spend,actions,date_start,date_stop', level: 'campaign', time_increment: 1, date_preset: 'last_30d' }, recordsPath: 'data', primaryKey: ['campaign_id', 'date_start'], cursorField: 'date_start', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'custom_audiences', path: '/act_{adAccountId}/customaudiences', params: { fields: 'id,name,subtype,approximate_count_lower_bound,approximate_count_upper_bound' }, recordsPath: 'data', primaryKey: 'id', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
    ],
  },

  {
    name: 'source-google-ads',
    displayName: 'Google Ads',
    description: 'Campaigns, ad groups and performance via GAQL search.',
    catalogSlug: 'google-ads', category: 'Applications', icon: 'googleads',
    baseUrl: 'https://googleads.googleapis.com/v17',
    auth: { type: 'bearer' },
    headers: { 'developer-token': '{developerToken}' },
    config: [
      { key: 'customerId', title: 'Customer ID (no dashes)', required: true },
      { key: 'accessToken', title: 'OAuth access token', secret: true, required: true },
      { key: 'developerToken', title: 'Developer token', secret: true, required: true },
      { key: 'loginCustomerId', title: 'Login customer ID (MCC)' },
    ],
    check: { path: '/customers/{customerId}/googleAds:search', method: 'POST' },
    resources: [
      {
        name: 'campaigns', path: '/customers/{customerId}/googleAds:search', method: 'POST',
        body: () => ({ query: 'SELECT campaign.id, campaign.name, campaign.status, campaign.start_date, campaign.end_date, campaign_budget.amount_micros FROM campaign ORDER BY campaign.id' }),
        recordsPath: 'results', primaryKey: 'campaign.id',
        map: (r) => ({ ...r.campaign, budget_amount_micros: r.campaign_budget?.amount_micros }),
      },
      {
        name: 'ad_groups', path: '/customers/{customerId}/googleAds:search', method: 'POST',
        body: () => ({ query: 'SELECT ad_group.id, ad_group.name, ad_group.status, ad_group.campaign, ad_group.type FROM ad_group' }),
        recordsPath: 'results', primaryKey: 'ad_group.id',
        map: (r) => r.ad_group,
      },
      {
        name: 'ads', path: '/customers/{customerId}/googleAds:search', method: 'POST',
        body: () => ({ query: 'SELECT ad_group_ad.ad.id, ad_group_ad.ad.name, ad_group_ad.status, ad_group_ad.ad_group FROM ad_group_ad' }),
        recordsPath: 'results', primaryKey: 'ad_group_ad.ad.id',
        map: (r) => ({ ...r.ad_group_ad?.ad, status: r.ad_group_ad?.status }),
      },
      {
        name: 'metrics', path: '/customers/{customerId}/googleAds:search', method: 'POST',
        body: () => ({ query: "SELECT segments.date, campaign.id, campaign.name, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions FROM campaign WHERE segments.date DURING LAST_30_DAYS" }),
        recordsPath: 'results', primaryKey: ['campaign.id', 'segments.date'],
        map: (r) => ({ date: r.segments?.date, campaign_id: r.campaign?.id, campaign_name: r.campaign?.name, ...r.metrics }),
      },
    ],
  },

  {
    name: 'source-linkedin-ads',
    displayName: 'LinkedIn Ad Analytics',
    description: 'Ad accounts, campaigns, creatives and analytics.',
    catalogSlug: 'linkedin-ads', category: 'Applications', icon: 'linkedin',
    baseUrl: 'https://api.linkedin.com/rest',
    auth: { type: 'bearer' },
    headers: { 'LinkedIn-Version': '202405', 'X-Restli-Protocol-Version': '2.0.0' },
    config: [{ key: 'accessToken', title: 'OAuth access token', secret: true, required: true }],
    check: { path: '/me' },
    resources: [
      { name: 'ad_accounts', path: '/adAccounts', params: { q: 'search' }, recordsPath: 'elements', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'start', limitParam: 'count', pageSize: 100, totalPath: 'paging.total' } },
      { name: 'campaigns', path: '/adCampaigns', params: { q: 'search' }, recordsPath: 'elements', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'start', limitParam: 'count', pageSize: 100, totalPath: 'paging.total' } },
      { name: 'campaign_groups', path: '/adCampaignGroups', params: { q: 'search' }, recordsPath: 'elements', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'start', limitParam: 'count', pageSize: 100, totalPath: 'paging.total' } },
      { name: 'creatives', path: '/creatives', params: { q: 'search' }, recordsPath: 'elements', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'start', limitParam: 'count', pageSize: 100, totalPath: 'paging.total' } },
    ],
  },

  {
    name: 'source-pinterest-ads',
    displayName: 'Pinterest Ads',
    description: 'Ad accounts, campaigns, ad groups, ads and analytics.',
    catalogSlug: 'pinterest-ads', category: 'Applications', icon: 'pinterest',
    baseUrl: 'https://api.pinterest.com/v5',
    auth: { type: 'bearer' },
    config: [{ key: 'accessToken', title: 'OAuth access token', secret: true, required: true }],
    check: { path: '/user_account' },
    resources: [
      { name: 'ad_accounts', path: '/ad_accounts', recordsPath: 'items', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'bookmark', cursorPath: 'bookmark' } },
      { name: 'campaigns', path: '/ad_accounts/{parentId}/campaigns', recordsPath: 'items', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'bookmark', cursorPath: 'bookmark' }, child: { parent: 'ad_accounts', path: (p) => `/ad_accounts/${p.id}/campaigns` } },
      { name: 'ad_groups', path: '/ad_accounts/{parentId}/ad_groups', recordsPath: 'items', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'bookmark', cursorPath: 'bookmark' }, child: { parent: 'ad_accounts', path: (p) => `/ad_accounts/${p.id}/ad_groups` } },
      { name: 'ads', path: '/ad_accounts/{parentId}/ads', recordsPath: 'items', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'bookmark', cursorPath: 'bookmark' }, child: { parent: 'ad_accounts', path: (p) => `/ad_accounts/${p.id}/ads` } },
      { name: 'boards', path: '/boards', recordsPath: 'items', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'bookmark', cursorPath: 'bookmark' } },
      { name: 'pins', path: '/pins', recordsPath: 'items', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'bookmark', cursorPath: 'bookmark' } },
    ],
  },

  {
    name: 'source-twitter-ads',
    displayName: 'X Ads',
    description: 'Ad accounts, campaigns, line items and promoted tweets.',
    catalogSlug: 'twitter-ads', category: 'Applications', icon: 'twitter',
    baseUrl: 'https://ads-api.twitter.com/12',
    auth: { type: 'bearer' },
    config: [{ key: 'accessToken', title: 'OAuth access token', secret: true, required: true }],
    check: { path: '/accounts' },
    resources: [
      { name: 'accounts', path: '/accounts', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'next_cursor' } },
      { name: 'campaigns', path: '/accounts/{parentId}/campaigns', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'next_cursor' }, child: { parent: 'accounts', path: (p) => `/accounts/${p.id}/campaigns` } },
      { name: 'line_items', path: '/accounts/{parentId}/line_items', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'next_cursor' }, child: { parent: 'accounts', path: (p) => `/accounts/${p.id}/line_items` } },
      { name: 'promoted_tweets', path: '/accounts/{parentId}/promoted_tweets', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'next_cursor' }, child: { parent: 'accounts', path: (p) => `/accounts/${p.id}/promoted_tweets` } },
      { name: 'funding_instruments', path: '/accounts/{parentId}/funding_instruments', recordsPath: 'data', primaryKey: 'id', child: { parent: 'accounts', path: (p) => `/accounts/${p.id}/funding_instruments` } },
    ],
  },

  {
    name: 'source-snapchat-ads',
    displayName: 'Snapchat Ads',
    description: 'Organizations, ad accounts, campaigns, ad squads and ads.',
    catalogSlug: 'snapchat-ads', category: 'Applications', icon: 'snapchat',
    baseUrl: 'https://adsapi.snapchat.com/v1',
    auth: { type: 'bearer' },
    config: [{ key: 'accessToken', title: 'OAuth access token', secret: true, required: true }],
    check: { path: '/me' },
    resources: [
      { name: 'organizations', path: '/me/organizations', recordsPath: 'organizations', primaryKey: 'organization.id', map: (x) => x.organization },
      { name: 'ad_accounts', path: '/organizations/{parentId}/adaccounts', recordsPath: 'adaccounts', primaryKey: 'adaccount.id', map: (x) => x.adaccount, child: { parent: 'organizations', path: (p) => `/organizations/${p.id}/adaccounts` } },
      { name: 'campaigns', path: '/adaccounts/{parentId}/campaigns', recordsPath: 'campaigns', primaryKey: 'campaign.id', map: (x) => x.campaign, child: { parent: 'ad_accounts', path: (p) => `/adaccounts/${p.id}/campaigns` } },
      { name: 'ad_squads', path: '/campaigns/{parentId}/adsquads', recordsPath: 'adsquads', primaryKey: 'adsquad.id', map: (x) => x.adsquad, child: { parent: 'campaigns', path: (p) => `/campaigns/${p.id}/adsquads` } },
      { name: 'ads', path: '/adsquads/{parentId}/ads', recordsPath: 'ads', primaryKey: 'ad.id', map: (x) => x.ad, child: { parent: 'ad_squads', path: (p) => `/adsquads/${p.id}/ads` } },
    ],
  },

  {
    name: 'source-google-analytics-4',
    displayName: 'Google Analytics 4',
    description: 'Daily session, traffic and engagement metrics via the Data API.',
    catalogSlug: 'google-analytics-4', category: 'Applications', icon: 'googleanalytics',
    baseUrl: 'https://analyticsdata.googleapis.com/v1beta',
    auth: { type: 'bearer' },
    config: [
      { key: 'propertyId', title: 'Property ID', required: true },
      { key: 'accessToken', title: 'OAuth access token', secret: true, required: true },
      { key: 'startDate', title: 'Start date', default: '30daysAgo', help: 'YYYY-MM-DD or NdaysAgo' },
    ],
    check: { path: '/properties/{propertyId}:runReport', method: 'POST' },
    resources: [
      {
        name: 'daily_metrics', path: '/properties/{propertyId}:runReport', method: 'POST',
        body: (cfg) => ({
          dateRanges: [{ startDate: cfg.startDate || '30daysAgo', endDate: 'today' }],
          dimensions: [{ name: 'date' }, { name: 'country' }, { name: 'sessionDefaultChannelGroup' }],
          metrics: [{ name: 'sessions' }, { name: 'totalUsers' }, { name: 'newUsers' }, { name: 'screenPageViews' }, { name: 'engagedSessions' }, { name: 'bounceRate' }, { name: 'averageSessionDuration' }],
          limit: 100000,
        }),
        recordsPath: 'rows',
        map: (r) => ({
          date: r.dimensionValues?.[0]?.value,
          country: r.dimensionValues?.[1]?.value,
          channel: r.dimensionValues?.[2]?.value,
          sessions: Number(r.metricValues?.[0]?.value || 0),
          total_users: Number(r.metricValues?.[1]?.value || 0),
          new_users: Number(r.metricValues?.[2]?.value || 0),
          page_views: Number(r.metricValues?.[3]?.value || 0),
          engaged_sessions: Number(r.metricValues?.[4]?.value || 0),
          bounce_rate: Number(r.metricValues?.[5]?.value || 0),
          avg_session_duration: Number(r.metricValues?.[6]?.value || 0),
        }),
        primaryKey: ['date', 'country', 'channel'],
        cursorField: 'date',
      },
    ],
  },

  {
    name: 'source-google-search-console',
    displayName: 'Google Search Console',
    description: 'Search analytics by query, page, country and device.',
    catalogSlug: 'google-search-console', category: 'Applications', icon: 'googlesearch',
    baseUrl: 'https://www.googleapis.com/webmasters/v3',
    auth: { type: 'bearer' },
    config: [
      { key: 'siteUrl', title: 'Site URL', required: true, help: 'e.g. https://example.com/ or sc-domain:example.com' },
      { key: 'accessToken', title: 'OAuth access token', secret: true, required: true },
      { key: 'startDate', title: 'Start date', default: '30daysAgo' },
    ],
    check: { path: '/sites' },
    resources: [
      {
        name: 'search_analytics', path: '/sites/{siteUrl}/searchanalytics/query', method: 'POST',
        body: (cfg) => ({
          startDate: cfg.startDate || '30daysAgo',
          endDate: new Date().toISOString().slice(0, 10),
          dimensions: ['date', 'query', 'page', 'country', 'device'],
          rowLimit: 25000,
        }),
        recordsPath: 'rows',
        map: (r) => ({
          date: r.keys?.[0], query: r.keys?.[1], page: r.keys?.[2],
          country: r.keys?.[3], device: r.keys?.[4],
          clicks: r.clicks, impressions: r.impressions, ctr: r.ctr, position: r.position,
        }),
        primaryKey: ['date', 'query', 'page', 'country', 'device'],
        cursorField: 'date',
      },
      { name: 'sitemaps', path: '/sites/{siteUrl}/sitemaps', recordsPath: 'sitemap', primaryKey: 'path' },
    ],
  },
];
