// CRM & sales specs — declarative definitions consumed by the SpecdSource engine.

module.exports = [
  {
    name: 'source-hubspot',
    displayName: 'HubSpot',
    description: 'Contacts, companies, deals, tickets and engagements from the HubSpot CRM.',
    catalogSlug: 'hubspot', category: 'Applications', icon: 'hubspot',
    baseUrl: 'https://api.hubapi.com',
    auth: { type: 'bearer' },
    config: [
      { key: 'accessToken', title: 'Private app access token', secret: true, required: true },
    ],
    check: { path: '/crm/v3/objects/contacts', params: { limit: 1 } },
    rateLimit: { minIntervalMs: 150 },
    resources: ['contacts', 'companies', 'deals', 'tickets', 'products', 'line_items'].map((obj) => ({
      name: obj,
      path: `/crm/v3/objects/${obj}`,
      recordsPath: 'results',
      primaryKey: 'id',
      cursorField: 'updatedAt',
      filterClientSide: true,
      pagination: { type: 'cursor', cursorParam: 'after', cursorPath: 'paging.next.after', limitParam: 'limit', pageSize: 100 },
    })),
  },

  {
    name: 'source-salesforce',
    displayName: 'Salesforce',
    description: 'Accounts, contacts, leads, opportunities and custom objects via SOQL.',
    catalogSlug: 'salesforce', category: 'Applications', icon: 'salesforce',
    baseUrl: '{instanceUrl}',
    auth: { type: 'oauth2_token' },
    config: [
      { key: 'instanceUrl', title: 'Instance URL', required: true, help: 'e.g. https://acme.my.salesforce.com' },
      { key: 'accessToken', title: 'OAuth access token', secret: true, required: true },
    ],
    check: { path: '/services/data/v59.0/limits' },
    resources: [
      { name: 'account', path: '/services/data/v59.0/query', params: { q: 'SELECT FIELDS(ALL) FROM Account ORDER BY LastModifiedDate LIMIT 200' }, recordsPath: 'records', pagination: { type: 'link', nextUrlPath: 'nextRecordsUrl' }, primaryKey: 'Id', cursorField: 'LastModifiedDate', filterClientSide: true },
      { name: 'contact', path: '/services/data/v59.0/query', params: { q: 'SELECT FIELDS(ALL) FROM Contact ORDER BY LastModifiedDate LIMIT 200' }, recordsPath: 'records', pagination: { type: 'link', nextUrlPath: 'nextRecordsUrl' }, primaryKey: 'Id', cursorField: 'LastModifiedDate', filterClientSide: true },
      { name: 'lead', path: '/services/data/v59.0/query', params: { q: 'SELECT FIELDS(ALL) FROM Lead ORDER BY LastModifiedDate LIMIT 200' }, recordsPath: 'records', pagination: { type: 'link', nextUrlPath: 'nextRecordsUrl' }, primaryKey: 'Id', cursorField: 'LastModifiedDate', filterClientSide: true },
      { name: 'opportunity', path: '/services/data/v59.0/query', params: { q: 'SELECT FIELDS(ALL) FROM Opportunity ORDER BY LastModifiedDate LIMIT 200' }, recordsPath: 'records', pagination: { type: 'link', nextUrlPath: 'nextRecordsUrl' }, primaryKey: 'Id', cursorField: 'LastModifiedDate', filterClientSide: true },
      { name: 'user', path: '/services/data/v59.0/query', params: { q: 'SELECT FIELDS(ALL) FROM User LIMIT 200' }, recordsPath: 'records', pagination: { type: 'link', nextUrlPath: 'nextRecordsUrl' }, primaryKey: 'Id' },
    ],
  },

  {
    name: 'source-pipedrive',
    displayName: 'Pipedrive',
    description: 'Deals, persons, organizations, activities and pipelines.',
    catalogSlug: 'pipedrive', category: 'Applications', icon: 'pipedrive',
    baseUrl: 'https://api.pipedrive.com/v1',
    auth: { type: 'query', param: 'api_token' },
    config: [
      { key: 'apiKey', title: 'API token', secret: true, required: true },
    ],
    check: { path: '/users/me' },
    resources: ['deals', 'persons', 'organizations', 'activities', 'pipelines', 'stages', 'users'].map((r) => ({
      name: r,
      path: `/${r}`,
      recordsPath: 'data',
      primaryKey: 'id',
      cursorField: r === 'activities' ? 'update_time' : (r === 'pipelines' || r === 'stages' ? 'update_time' : 'update_time'),
      incrementalParam: 'since_timestamp',
      pagination: { type: 'cursor', cursorParam: 'start', cursorPath: 'additional_data.pagination.next_start', limitParam: 'limit', pageSize: 100 },
    })),
  },

  {
    name: 'source-close',
    displayName: 'Close',
    description: 'Leads, contacts, opportunities and activities from Close CRM.',
    catalogSlug: 'close', category: 'Applications', icon: 'close',
    baseUrl: 'https://api.close.com/api/v1',
    auth: { type: 'basic', username: '{apiKey}', password: '' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/me' },
    resources: [
      { name: 'lead', path: '/lead', recordsPath: 'data', primaryKey: 'id', cursorField: 'date_updated', pagination: { type: 'offset', offsetParam: '_skip', limitParam: '_limit', pageSize: 100, totalPath: 'total_results' } },
      { name: 'contact', path: '/contact', recordsPath: 'data', primaryKey: 'id', cursorField: 'date_updated', pagination: { type: 'offset', offsetParam: '_skip', limitParam: '_limit', pageSize: 100 } },
      { name: 'opportunity', path: '/opportunity', recordsPath: 'data', primaryKey: 'id', cursorField: 'date_updated', pagination: { type: 'offset', offsetParam: '_skip', limitParam: '_limit', pageSize: 100 } },
      { name: 'activity', path: '/activity', recordsPath: 'data', primaryKey: 'id', cursorField: 'date_created', pagination: { type: 'offset', offsetParam: '_skip', limitParam: '_limit', pageSize: 100 } },
      { name: 'user', path: '/user', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'offset', offsetParam: '_skip', limitParam: '_limit', pageSize: 100 } },
    ],
  },

  {
    name: 'source-zoho-crm',
    displayName: 'Zoho CRM',
    description: 'Leads, contacts, accounts and deals from Zoho CRM.',
    catalogSlug: 'zoho-crm', category: 'Applications', icon: 'zoho',
    baseUrl: 'https://www.zohoapis.com/crm/v7',
    auth: { type: 'bearer' },
    config: [{ key: 'accessToken', title: 'OAuth access token', secret: true, required: true }],
    check: { path: '/Leads', params: { per_page: 1 } },
    resources: ['Leads', 'Contacts', 'Accounts', 'Deals', 'Tasks', 'Events', 'Calls'].map((m) => ({
      name: m.toLowerCase(),
      path: `/${m}`,
      recordsPath: 'data',
      primaryKey: 'id',
      cursorField: 'Modified_Time',
      filterClientSide: true,
      pagination: { type: 'cursor', cursorParam: 'page_token', cursorPath: 'info.next_page_token', limitParam: 'per_page', pageSize: 200 },
    })),
  },

  {
    name: 'source-insightly',
    displayName: 'Insightly',
    description: 'Contacts, leads, organisations, opportunities and tasks.',
    catalogSlug: 'insightly', category: 'Applications', icon: 'insightly',
    baseUrl: 'https://api.insightly.com/v3.1',
    auth: { type: 'basic', username: '{apiKey}', password: '' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/Contacts', params: { top: 1 } },
    resources: ['Contacts', 'Leads', 'Organisations', 'Opportunities', 'Tasks', 'Events', 'Projects'].map((m) => ({
      name: m.toLowerCase(),
      path: `/${m}`,
      recordsPath: null,
      primaryKey: m === 'Organisations' ? 'ORGANISATION_ID' : `${m.replace(/s$/, '').toUpperCase()}_ID`,
      cursorField: 'DATE_UPDATED_UTC',
      filterClientSide: true,
      pagination: { type: 'offset', offsetParam: 'skip', limitParam: 'top', pageSize: 500 },
    })),
  },

  {
    name: 'source-attio',
    displayName: 'Attio',
    description: 'People, companies and records from the Attio workspace.',
    catalogSlug: 'attio', category: 'Applications', icon: 'attio',
    baseUrl: 'https://api.attio.com/v2',
    auth: { type: 'bearer' },
    config: [{ key: 'accessToken', title: 'API token', secret: true, required: true }],
    check: { path: '/self' },
    resources: [
      { name: 'people', path: '/objects/people/records/query', method: 'POST', body: { filter: {}, sorts: [{ attribute: 'last_interaction', direction: 'desc' }] }, recordsPath: 'data', primaryKey: 'id.record_id', pagination: { type: 'offset', place: 'body', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'companies', path: '/objects/companies/records/query', method: 'POST', body: {}, recordsPath: 'data', primaryKey: 'id.record_id', pagination: { type: 'offset', place: 'body', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'workspace_members', path: '/workspace_members', recordsPath: 'data', primaryKey: 'id.workspace_member_id' },
    ],
  },

  {
    name: 'source-copper',
    displayName: 'Copper',
    description: 'People, companies, opportunities and activities from Copper CRM.',
    catalogSlug: 'copper', category: 'Applications', icon: 'copper',
    baseUrl: 'https://api.copper.com/developer_api/v1',
    auth: { type: 'token_header', header: 'X-PW-AccessToken' },
    headers: { 'X-PW-Application': 'developer_api', 'X-PW-UserEmail': '{userEmail}' },
    config: [
      { key: 'apiKey', title: 'API token', secret: true, required: true },
      { key: 'userEmail', title: 'User email', required: true },
    ],
    check: { path: '/account' },
    resources: ['people', 'companies', 'opportunities', 'leads', 'activities'].map((r) => ({
      name: r,
      path: `/${r}/search`,
      method: 'POST',
      body: { page_size: 200, sort_by: 'date_modified', sort_direction: 'asc' },
      recordsPath: null,
      primaryKey: 'id',
      cursorField: 'date_modified',
      filterClientSide: true,
      pagination: { type: 'page', place: 'body', pageParam: 'page_number', limitParam: 'page_size', pageSize: 200 },
    })),
  },
];
