// E-commerce & payments specs.

module.exports = [
  {
    name: 'source-shopify',
    displayName: 'Shopify',
    description: 'Products, orders, customers, inventory and collections.',
    catalogSlug: 'shopify', category: 'Applications', icon: 'shopify',
    baseUrl: 'https://{shop}.myshopify.com/admin/api/2024-10',
    auth: { type: 'token_header', header: 'X-Shopify-Access-Token' },
    config: [
      { key: 'shop', title: 'Shop domain', required: true, help: 'mystore in mystore.myshopify.com' },
      { key: 'accessToken', title: 'Admin API access token', secret: true, required: true },
    ],
    check: { path: '/shop.json' },
    rateLimit: { minIntervalMs: 500 },
    resources: [
      { name: 'products', path: '/products.json', recordsPath: 'products', primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_at_min', pagination: { type: 'link', linkHeader: true } },
      { name: 'orders', path: '/orders.json', params: { status: 'any' }, recordsPath: 'orders', primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_at_min', pagination: { type: 'link', linkHeader: true } },
      { name: 'customers', path: '/customers.json', recordsPath: 'customers', primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_at_min', pagination: { type: 'link', linkHeader: true } },
      { name: 'inventory_items', path: '/inventory_items.json', params: { limit: 250 }, recordsPath: 'inventory_items', primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_at_min', pagination: { type: 'link', linkHeader: true } },
      { name: 'custom_collections', path: '/custom_collections.json', recordsPath: 'custom_collections', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'link', linkHeader: true } },
      { name: 'smart_collections', path: '/smart_collections.json', recordsPath: 'smart_collections', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'link', linkHeader: true } },
      { name: 'discounts', path: '/price_rules.json', recordsPath: 'price_rules', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'link', linkHeader: true } },
      { name: 'locations', path: '/locations.json', recordsPath: 'locations', primaryKey: 'id' },
      { name: 'checkouts', path: '/checkouts.json', recordsPath: 'checkouts', primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_at_min', pagination: { type: 'link', linkHeader: true } },
      { name: 'transactions', path: '/orders/{parentId}/transactions.json', recordsPath: 'transactions', primaryKey: 'id', child: { parent: 'orders', path: (p) => `/orders/${p.id}/transactions.json` } },
    ],
  },

  {
    name: 'source-square',
    displayName: 'Square',
    description: 'Payments, orders, customers, catalog items and locations.',
    catalogSlug: 'square', category: 'Applications', icon: 'square',
    baseUrl: 'https://connect.squareup.com/v2',
    auth: { type: 'bearer' },
    headers: { 'Square-Version': '2024-10-17' },
    config: [{ key: 'accessToken', title: 'Access token', secret: true, required: true }],
    check: { path: '/locations' },
    resources: [
      { name: 'locations', path: '/locations', recordsPath: 'locations', primaryKey: 'id' },
      { name: 'payments', path: '/payments', recordsPath: 'payments', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'cursor' } },
      { name: 'customers', path: '/customers', recordsPath: 'customers', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'cursor' } },
      { name: 'refunds', path: '/refunds', recordsPath: 'refunds', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'cursor' } },
      { name: 'disputes', path: '/disputes', recordsPath: 'disputes', primaryKey: 'dispute_id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'cursor' } },
      { name: 'catalog', path: '/catalog/list', recordsPath: 'objects', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'cursor' } },
      { name: 'invoices', path: '/invoices', recordsPath: 'invoices', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'cursor', cursorParam: 'cursor', cursorPath: 'cursor' } },
      { name: 'orders', path: '/orders/search', method: 'POST', body: { limit: 500, query: { sort: { sort_field: 'UPDATED_AT', sort_order: 'ASC' } } }, recordsPath: 'orders', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'cursor', place: 'body', cursorParam: 'cursor', cursorPath: 'cursor' } },
    ],
  },

  {
    name: 'source-chargebee',
    displayName: 'Chargebee',
    description: 'Customers, subscriptions, invoices, plans and coupons.',
    catalogSlug: 'chargebee', catalogName: 'Chargebee Product Catalog 2.0', category: 'Applications', icon: 'chargebee',
    baseUrl: 'https://{site}.chargebee.com/api/v2',
    auth: { type: 'basic', username: '{apiKey}', password: '' },
    config: [
      { key: 'site', title: 'Site', required: true, help: 'acme in acme.chargebee.com' },
      { key: 'apiKey', title: 'API key', secret: true, required: true },
    ],
    check: { path: '/customers', params: { limit: 1 } },
    rateLimit: { minIntervalMs: 300 },
    resources: ['customers', 'subscriptions', 'invoices', 'orders', 'plans', 'addons', 'coupons', 'credit_notes', 'transactions', 'hosted_pages'].map((r) => ({
      name: r,
      path: `/${r}`,
      recordsPath: 'list',
      primaryKey: `${r.replace(/s$/, '')}.id`,
      cursorField: `${r.replace(/s$/, '')}.updated_at`,
      filterClientSide: true,
      pagination: { type: 'cursor', cursorParam: 'offset', cursorPath: 'next_offset', limitParam: 'limit', pageSize: 100 },
      map: (x) => x[r.replace(/s$/, '')] ? { ...x[r.replace(/s$/, '')], _entity: r.replace(/s$/, '') } : x,
    })),
  },

  {
    name: 'source-recurly',
    displayName: 'Recurly',
    description: 'Accounts, subscriptions, invoices, plans and transactions.',
    catalogSlug: 'recurly', category: 'Applications', icon: 'recurly',
    baseUrl: 'https://v3.recurly.com',
    auth: { type: 'basic', username: '{apiKey}', password: '' },
    config: [{ key: 'apiKey', title: 'Private API key', secret: true, required: true }],
    check: { path: '/accounts', params: { limit: 1 } },
    resources: ['accounts', 'subscriptions', 'invoices', 'plans', 'items', 'coupons', 'transactions', 'credit_memos'].map((r) => ({
      name: r,
      path: `/${r}`,
      params: { sort: 'updated_at', order: 'asc' },
      recordsPath: 'data',
      primaryKey: 'id',
      cursorField: 'updated_at',
      incrementalParam: 'begin_time',
      pagination: { type: 'link', nextUrlPath: 'next' },
    })),
  },

  {
    name: 'source-woocommerce',
    displayName: 'WooCommerce',
    description: 'Orders, products, customers, coupons and reviews.',
    catalogSlug: 'woocommerce', category: 'Applications', icon: 'woocommerce',
    baseUrl: 'https://{site}/wp-json/wc/v3',
    auth: { type: 'basic', username: '{consumerKey}', password: '{consumerSecret}' },
    config: [
      { key: 'site', title: 'Store URL (no scheme path)', required: true, help: 'e.g. store.example.com' },
      { key: 'consumerKey', title: 'Consumer key', required: true },
      { key: 'consumerSecret', title: 'Consumer secret', secret: true, required: true },
    ],
    check: { path: '/system_status' },
    resources: [
      { name: 'orders', path: '/orders', recordsPath: null, primaryKey: 'id', cursorField: 'date_modified_gmt', incrementalParam: 'modified_after', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 100 } },
      { name: 'products', path: '/products', recordsPath: null, primaryKey: 'id', cursorField: 'date_modified_gmt', incrementalParam: 'modified_after', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 100 } },
      { name: 'customers', path: '/customers', recordsPath: null, primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 100 } },
      { name: 'coupons', path: '/coupons', recordsPath: null, primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 100 } },
      { name: 'reviews', path: '/products/reviews', recordsPath: null, primaryKey: 'id', cursorField: 'date_created_gmt', incrementalParam: 'after', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 100 } },
      { name: 'categories', path: '/products/categories', recordsPath: null, primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 100 } },
      { name: 'refunds', path: '/orders/{parentId}/refunds', recordsPath: null, primaryKey: 'id', child: { parent: 'orders', path: (p) => `/orders/${p.id}/refunds` } },
    ],
  },

  {
    name: 'source-bigcommerce',
    displayName: 'BigCommerce',
    description: 'Products, orders, customers, carts and categories.',
    catalogSlug: 'bigcommerce', category: 'Applications', icon: 'bigcommerce',
    baseUrl: 'https://api.bigcommerce.com/stores/{storeHash}',
    auth: { type: 'token_header', header: 'X-Auth-Token' },
    config: [
      { key: 'storeHash', title: 'Store hash', required: true },
      { key: 'accessToken', title: 'Access token', secret: true, required: true },
    ],
    check: { path: '/v3/catalog/summary' },
    resources: [
      { name: 'products', path: '/v3/catalog/products', recordsPath: 'data', primaryKey: 'id', cursorField: 'date_modified', incrementalParam: 'date_modified:min', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 250 } },
      { name: 'categories', path: '/v3/catalog/categories', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 250 } },
      { name: 'brands', path: '/v3/catalog/brands', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 250 } },
      { name: 'customers', path: '/v3/customers', recordsPath: 'data', primaryKey: 'id', cursorField: 'date_modified', incrementalParam: 'date_modified:min', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 250 } },
      { name: 'orders', path: '/v2/orders', recordsPath: null, primaryKey: 'id', cursorField: 'date_modified', incrementalParam: 'min_date_modified', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 250 } },
      { name: 'carts', path: '/v3/carts', recordsPath: 'data', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 250 } },
    ],
  },

  {
    name: 'source-magento',
    displayName: 'Magento (Adobe Commerce)',
    description: 'Products, orders, customers and invoices.',
    catalogSlug: 'adobe-commerce', category: 'Applications', icon: 'magento',
    baseUrl: 'https://{host}/rest/V1',
    auth: { type: 'bearer' },
    config: [
      { key: 'host', title: 'Store host', required: true, help: 'magento.example.com' },
      { key: 'accessToken', title: 'Integration access token', secret: true, required: true },
    ],
    check: { path: '/store/storeConfigs' },
    resources: [
      { name: 'products', path: '/products', params: { 'searchCriteria[pageSize]': 100 }, recordsPath: 'items', primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'searchCriteria[filterGroups][0][filters][0][value]', pagination: { type: 'page', pageParam: 'searchCriteria[currentPage]', pageSize: 100 } },
      { name: 'orders', path: '/orders', params: { 'searchCriteria[pageSize]': 100 }, recordsPath: 'items', primaryKey: 'entity_id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'page', pageParam: 'searchCriteria[currentPage]', pageSize: 100 } },
      { name: 'customers', path: '/customers/search', params: { 'searchCriteria[pageSize]': 100 }, recordsPath: 'items', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'page', pageParam: 'searchCriteria[currentPage]', pageSize: 100 } },
      { name: 'invoices', path: '/invoices', params: { 'searchCriteria[pageSize]': 100 }, recordsPath: 'items', primaryKey: 'entity_id', pagination: { type: 'page', pageParam: 'searchCriteria[currentPage]', pageSize: 100 } },
    ],
  },
];
