// HRIS, recruiting & payroll specs.

module.exports = [
  {
    name: 'source-bamboohr',
    displayName: 'BambooHR',
    description: 'Employee directory, time off, job info and company files.',
    catalogSlug: 'bamboohr', category: 'Applications', icon: 'bamboohr',
    baseUrl: 'https://api.bamboohr.com/api/gateway.php/{company}/v1',
    auth: { type: 'basic', username: '{apiKey}', password: 'x' },
    headers: { Accept: 'application/json' },
    config: [
      { key: 'company', title: 'Company subdomain', required: true },
      { key: 'apiKey', title: 'API key', secret: true, required: true },
    ],
    check: { path: '/employees/directory' },
    resources: [
      { name: 'employees', path: '/employees/directory', recordsPath: 'employees', primaryKey: 'id' },
      { name: 'time_off_requests', path: '/time_off/requests', params: { status: 'approved' }, recordsPath: null, primaryKey: 'id' },
      { name: 'whos_out', path: '/time_off/whos_out', recordsPath: null, primaryKey: 'employeeId' },
      { name: 'job_info', path: '/employees/{parentId}/tables/jobInfo', recordsPath: null, primaryKey: 'id', child: { parent: 'employees', path: (p) => `/employees/${p.id}/tables/jobInfo` } },
      { name: 'employment_status', path: '/employees/{parentId}/tables/employmentStatus', recordsPath: null, primaryKey: 'id', child: { parent: 'employees', path: (p) => `/employees/${p.id}/tables/employmentStatus` } },
    ],
  },

  {
    name: 'source-greenhouse',
    displayName: 'Greenhouse',
    description: 'Candidates, applications, jobs, offers and users.',
    catalogSlug: 'greenhouse', category: 'Applications', icon: 'greenhouse',
    baseUrl: 'https://harvest.greenhouse.io/v1',
    auth: { type: 'basic', username: '{apiKey}', password: '' },
    config: [{ key: 'apiKey', title: 'Harvest API key', secret: true, required: true }],
    check: { path: '/users' },
    resources: [
      { name: 'candidates', path: '/candidates', recordsPath: null, primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_after', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
      { name: 'applications', path: '/applications', recordsPath: null, primaryKey: 'id', cursorField: 'last_activity_at', filterClientSide: true, pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
      { name: 'jobs', path: '/jobs', recordsPath: null, primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_after', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
      { name: 'offers', path: '/offers', recordsPath: null, primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true, pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
      { name: 'users', path: '/users', recordsPath: null, primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
      { name: 'job_posts', path: '/job_posts', recordsPath: null, primaryKey: 'id', cursorField: 'updated_at', incrementalParam: 'updated_after', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
      { name: 'departments', path: '/departments', recordsPath: null, primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
      { name: 'offices', path: '/offices', recordsPath: null, primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'per_page', pageSize: 500 } },
    ],
  },

  {
    name: 'source-lever',
    displayName: 'Lever',
    description: 'Postings, opportunities, users and stages.',
    catalogSlug: 'lever', category: 'Applications', icon: 'lever',
    baseUrl: 'https://api.lever.co/v1',
    auth: { type: 'basic', username: '{apiKey}', password: '' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/postings', params: { limit: 1 } },
    resources: [
      { name: 'postings', path: '/postings', recordsPath: 'data', primaryKey: 'id', cursorField: 'updatedAt', incrementalParam: 'updated_at_start', pagination: { type: 'cursor', cursorParam: 'offset', cursorPath: 'next', limitParam: 'limit', pageSize: 100 } },
      { name: 'opportunities', path: '/opportunities', recordsPath: 'data', primaryKey: 'id', cursorField: 'updatedAt', incrementalParam: 'updated_at_start', pagination: { type: 'cursor', cursorParam: 'offset', cursorPath: 'next', limitParam: 'limit', pageSize: 100 } },
      { name: 'users', path: '/users', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'cursor', cursorParam: 'offset', cursorPath: 'next', limitParam: 'limit', pageSize: 100 } },
      { name: 'stages', path: '/stages', recordsPath: 'data', primaryKey: 'id' },
      { name: 'archive_reasons', path: '/archive_reasons', recordsPath: 'data', primaryKey: 'id' },
      { name: 'sources', path: '/sources', recordsPath: 'data', primaryKey: 'id' },
    ],
  },

  {
    name: 'source-workable',
    displayName: 'Workable',
    description: 'Jobs, candidates, members and pipeline stages.',
    catalogSlug: 'workable', category: 'Applications', icon: 'workable',
    baseUrl: 'https://{subdomain}.workable.com/spi/v3',
    auth: { type: 'bearer' },
    config: [
      { key: 'subdomain', title: 'Subdomain', required: true },
      { key: 'accessToken', title: 'Access token', secret: true, required: true },
    ],
    check: { path: '/accounts' },
    resources: [
      { name: 'jobs', path: '/jobs', recordsPath: 'jobs', primaryKey: 'shortcode', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'candidates', path: '/jobs/{parentId}/candidates', recordsPath: 'candidates', primaryKey: 'id', pagination: { type: 'link', nextUrlPath: 'paging.next' }, child: { parent: 'jobs', path: (p) => `/jobs/${p.shortcode}/candidates` } },
      { name: 'members', path: '/members', recordsPath: 'members', primaryKey: 'id', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'stages', path: '/jobs/{parentId}/stages', recordsPath: 'stages', primaryKey: 'slug', child: { parent: 'jobs', path: (p) => `/jobs/${p.shortcode}/stages` } },
    ],
  },

  {
    name: 'source-ashby',
    displayName: 'Ashby',
    description: 'Candidates, applications, jobs and interview schedules.',
    catalogSlug: 'ashby', category: 'Applications', icon: 'ashby',
    baseUrl: 'https://api.ashbyhq.com',
    auth: { type: 'basic', username: '{apiKey}', password: '' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/apiKey.info', method: 'POST' },
    resources: [
      { name: 'candidates', path: '/candidate.list', method: 'POST', body: {}, recordsPath: 'results', primaryKey: 'id', pagination: { type: 'cursor', place: 'body', cursorParam: 'cursor', cursorPath: 'nextCursor' } },
      { name: 'applications', path: '/application.list', method: 'POST', body: {}, recordsPath: 'results', primaryKey: 'id', pagination: { type: 'cursor', place: 'body', cursorParam: 'cursor', cursorPath: 'nextCursor' } },
      { name: 'jobs', path: '/job.list', method: 'POST', body: {}, recordsPath: 'results', primaryKey: 'id', pagination: { type: 'cursor', place: 'body', cursorParam: 'cursor', cursorPath: 'nextCursor' } },
      { name: 'offers', path: '/offer.list', method: 'POST', body: {}, recordsPath: 'results', primaryKey: 'id', pagination: { type: 'cursor', place: 'body', cursorParam: 'cursor', cursorPath: 'nextCursor' } },
      { name: 'departments', path: '/department.list', method: 'POST', body: {}, recordsPath: 'results', primaryKey: 'id' },
      { name: 'locations', path: '/location.list', method: 'POST', body: {}, recordsPath: 'results', primaryKey: 'id' },
      { name: 'interview_schedules', path: '/interviewSchedule.list', method: 'POST', body: {}, recordsPath: 'results', primaryKey: 'id', pagination: { type: 'cursor', place: 'body', cursorParam: 'cursor', cursorPath: 'nextCursor' } },
    ],
  },

  {
    name: 'source-personio',
    displayName: 'Personio',
    description: 'Employees, absences, attendances and documents.',
    catalogSlug: 'personio', category: 'Applications', icon: 'personio',
    baseUrl: 'https://api.personio.de/v1',
    auth: { type: 'oauth2_cc', tokenUrl: 'https://api.personio.de/v1/auth', json: true, tokenPath: 'data.token', clientIdKey: 'client_id', clientSecretKey: 'client_secret' },
    config: [
      { key: 'clientId', title: 'Client ID', required: true },
      { key: 'clientSecret', title: 'Client secret', secret: true, required: true },
    ],
    check: { path: '/company/employees', params: { limit: 1 } },
    resources: [
      { name: 'employees', path: '/company/employees', recordsPath: 'data', primaryKey: 'id', cursorField: 'attributes.last_modified_at.value', filterClientSide: true, pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 200 } },
      { name: 'absences', path: '/company/time-offs', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 200 } },
      { name: 'absence_types', path: '/company/time-off-types', recordsPath: 'data', primaryKey: 'id' },
      { name: 'attendances', path: '/company/attendances', recordsPath: 'data', primaryKey: 'id', cursorField: 'attributes.updated_at', filterClientSide: true, pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 200 } },
      { name: 'departments', path: '/company/departments', recordsPath: 'data', primaryKey: 'id' },
      { name: 'offices', path: '/company/offices', recordsPath: 'data', primaryKey: 'id' },
    ],
  },

  {
    name: 'source-gusto',
    displayName: 'Gusto',
    description: 'Employees, payrolls, benefits and time off.',
    catalogSlug: 'gusto', category: 'Applications', icon: 'gusto',
    baseUrl: 'https://api.gusto.com/v1',
    auth: { type: 'bearer' },
    config: [
      { key: 'accessToken', title: 'API token', secret: true, required: true },
      { key: 'companyId', title: 'Company ID', required: true },
    ],
    check: { path: '/companies/{companyId}' },
    resources: [
      { name: 'employees', path: '/companies/{companyId}/employees', recordsPath: null, primaryKey: 'uuid' },
      { name: 'payrolls', path: '/companies/{companyId}/payrolls', recordsPath: null, primaryKey: 'payroll_uuid' },
      { name: 'contractors', path: '/companies/{companyId}/contractors', recordsPath: null, primaryKey: 'uuid' },
      { name: 'benefits', path: '/companies/{companyId}/company_benefits', recordsPath: null, primaryKey: 'uuid' },
      { name: 'departments', path: '/companies/{companyId}/departments', recordsPath: null, primaryKey: 'uuid' },
      { name: 'jobs', path: '/companies/{companyId}/jobs', recordsPath: null, primaryKey: 'uuid' },
      { name: 'time_off', path: '/companies/{companyId}/time_off_requests', recordsPath: null, primaryKey: 'id' },
    ],
  },

  {
    name: 'source-smartrecruiters',
    displayName: 'SmartRecruiters',
    description: 'Jobs, candidates, offers and hiring team data.',
    catalogSlug: 'smartrecruiters', category: 'Applications', icon: 'smartrecruiters',
    baseUrl: 'https://api.smartrecruiters.com/v1',
    auth: { type: 'token_header', header: 'X-SmartToken' },
    config: [{ key: 'apiKey', title: 'SmartToken', secret: true, required: true }],
    check: { path: '/users/me' },
    resources: [
      { name: 'jobs', path: '/jobs', recordsPath: 'content', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100, totalPath: 'totalFound' } },
      { name: 'candidates', path: '/candidates', recordsPath: 'content', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100, totalPath: 'totalFound' } },
      { name: 'departments', path: '/departments', recordsPath: 'content', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'offers', path: '/offers', recordsPath: 'content', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
    ],
  },

  {
    name: 'source-factorial',
    displayName: 'Factorial',
    description: 'Employees, time off, shifts and contracts.',
    catalogSlug: 'factorial', category: 'Applications', icon: 'factorial',
    baseUrl: 'https://api.factorialhr.com/api/v2',
    auth: { type: 'api_key', header: 'x-api-key' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/core/employees', params: { limit: 1 } },
    resources: [
      { name: 'employees', path: '/core/employees', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 100 } },
      { name: 'time_off', path: '/timeoff/leaves', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 100 } },
      { name: 'shifts', path: '/time/shifts', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 100 } },
      { name: 'contracts', path: '/payroll/contracts', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'limit', pageSize: 100 } },
      { name: 'workplaces', path: '/core/locations', recordsPath: 'data', primaryKey: 'id' },
    ],
  },

  {
    name: 'source-hibob',
    displayName: 'HiBob',
    description: 'People, org structure, time off and custom tables.',
    catalogSlug: 'hibob', category: 'Applications', icon: 'hibob',
    baseUrl: 'https://api.hibob.com/v1',
    auth: { type: 'basic', username: '{serviceUserId}', password: '{serviceUserToken}' },
    config: [
      { key: 'serviceUserId', title: 'Service user ID', required: true },
      { key: 'serviceUserToken', title: 'Service user token', secret: true, required: true },
    ],
    check: { path: '/company/named-lists' },
    resources: [
      { name: 'people', path: '/people/search', method: 'POST', body: { showInactive: true }, recordsPath: 'employees', primaryKey: 'id' },
      { name: 'workflows', path: '/workflows', recordsPath: null, primaryKey: 'id' },
      { name: 'timeoff', path: '/timeoff/employees/{parentId}/requests', recordsPath: 'requests', primaryKey: 'requestId', child: { parent: 'people', path: (p) => `/timeoff/employees/${p.id}/requests` } },
    ],
  },
];
