// Email, marketing automation & customer engagement specs.

module.exports = [
  {
    name: 'source-mailchimp',
    displayName: 'Mailchimp',
    description: 'Lists, members, campaigns, automations and reports.',
    catalogSlug: 'mailchimp', category: 'Applications', icon: 'mailchimp',
    baseUrl: 'https://{dc}.api.mailchimp.com/3.0',
    auth: { type: 'basic', username: 'datamove', password: '{apiKey}' },
    config: [
      { key: 'apiKey', title: 'API key', secret: true, required: true, help: 'Ends with -usX' },
      { key: 'dc', title: 'Data center', required: true, help: 'us6, eu1, ... (suffix of your API key)' },
    ],
    check: { path: '/ping' },
    resources: [
      { name: 'lists', path: '/lists', recordsPath: 'lists', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 100, totalPath: 'total_items' } },
      { name: 'members', path: '/lists/{parentId}/members', recordsPath: 'members', primaryKey: 'id', cursorField: 'last_changed', incrementalParam: 'since_last_changed', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 1000 }, child: { parent: 'lists', path: (p) => `/lists/${p.id}/members` } },
      { name: 'campaigns', path: '/campaigns', recordsPath: 'campaigns', primaryKey: 'id', cursorField: 'send_time', filterClientSide: true, pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 100, totalPath: 'total_items' } },
      { name: 'automations', path: '/automations', recordsPath: 'automations', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 100, totalPath: 'total_items' } },
      { name: 'templates', path: '/templates', recordsPath: 'templates', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 100, totalPath: 'total_items' } },
      { name: 'reports', path: '/reports', recordsPath: 'reports', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 100, totalPath: 'total_items' } },
    ],
  },

  {
    name: 'source-klaviyo',
    displayName: 'Klaviyo',
    description: 'Profiles, lists, segments, campaigns and metrics.',
    catalogSlug: 'klaviyo', category: 'Applications', icon: 'klaviyo',
    baseUrl: 'https://a.klaviyo.com/api',
    auth: { type: 'raw_header', header: 'Authorization', value: 'Klaviyo-API-Key {apiKey}' },
    headers: { revision: '2024-10-15' },
    config: [{ key: 'apiKey', title: 'Private API key', secret: true, required: true }],
    check: { path: '/accounts/' },
    resources: [
      { name: 'profiles', path: '/profiles/', recordsPath: 'data', primaryKey: 'id', cursorField: 'attributes.updated', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'links.next' } },
      { name: 'lists', path: '/lists/', recordsPath: 'data', primaryKey: 'id', cursorField: 'attributes.updated', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'links.next' } },
      { name: 'segments', path: '/segments/', recordsPath: 'data', primaryKey: 'id', cursorField: 'attributes.updated', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'links.next' } },
      { name: 'campaigns', path: '/campaigns/', recordsPath: 'data', primaryKey: 'id', cursorField: 'attributes.updated_at', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'links.next' } },
      { name: 'metrics', path: '/metrics/', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'link', nextUrlPath: 'links.next' } },
      { name: 'flows', path: '/flows/', recordsPath: 'data', primaryKey: 'id', pagination: { type: 'link', nextUrlPath: 'links.next' } },
      { name: 'events', path: '/events/', recordsPath: 'data', primaryKey: 'id', cursorField: 'attributes.datetime', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'links.next' } },
    ],
  },

  {
    name: 'source-sendgrid',
    displayName: 'SendGrid',
    description: 'Contacts, lists, campaigns, templates and suppression data.',
    catalogSlug: 'sendgrid', category: 'Applications', icon: 'sendgrid',
    baseUrl: 'https://api.sendgrid.com/v3',
    auth: { type: 'bearer' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/user/profile' },
    resources: [
      { name: 'lists', path: '/marketing/lists', recordsPath: 'result', primaryKey: 'id' },
      { name: 'contacts', path: '/marketing/contacts', recordsPath: 'result', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true },
      { name: 'single_sends', path: '/marketing/singlesends', recordsPath: 'result', primaryKey: 'id', cursorField: 'updated_at', filterClientSide: true },
      { name: 'templates', path: '/templates', params: { generations: 'dynamic' }, recordsPath: 'result', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', limitParam: 'page_size', pageSize: 200 } },
      { name: 'suppression_groups', path: '/asm/groups', recordsPath: null, primaryKey: 'id' },
      { name: 'global_unsubscribes', path: '/suppression/unsubscribes', recordsPath: null, primaryKey: 'email', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 500 } },
      { name: 'bounces', path: '/suppression/bounces', recordsPath: null, primaryKey: 'email', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 500 } },
      { name: 'senders', path: '/senders', recordsPath: null, primaryKey: 'id' },
    ],
  },

  {
    name: 'source-mailgun',
    displayName: 'Mailgun',
    description: 'Domains, events, lists, suppressions and templates.',
    catalogSlug: 'mailgun', category: 'Applications', icon: 'mailgun',
    baseUrl: 'https://api.mailgun.net/v3',
    auth: { type: 'basic', username: 'api', password: '{apiKey}' },
    config: [
      { key: 'apiKey', title: 'Private API key', secret: true, required: true },
      { key: 'domain', title: 'Domain', required: true, help: 'mg.example.com' },
    ],
    check: { path: '/domains' },
    resources: [
      { name: 'domains', path: '/domains', recordsPath: 'items', primaryKey: 'name', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'events', path: '/{domain}/events', recordsPath: 'items', primaryKey: 'id', cursorField: 'timestamp', filterClientSide: true, pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'lists', path: '/lists/pages', recordsPath: 'items', primaryKey: 'address', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'bounces', path: '/{domain}/bounces', recordsPath: 'items', primaryKey: 'address', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'unsubscribes', path: '/{domain}/unsubscribes', recordsPath: 'items', primaryKey: 'address', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'complaints', path: '/{domain}/complaints', recordsPath: 'items', primaryKey: 'address', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
      { name: 'templates', path: '/{domain}/templates', recordsPath: 'items', primaryKey: 'name', pagination: { type: 'link', nextUrlPath: 'paging.next' } },
    ],
  },

  {
    name: 'source-customerio',
    displayName: 'Customer.io',
    description: 'Campaigns, customers, newsletters, segments and broadcasts.',
    catalogSlug: 'customer.io', category: 'Applications', icon: 'customerio',
    baseUrl: 'https://track.customer.io/api/v1',
    auth: { type: 'basic', username: '{siteId}', password: '{apiKey}' },
    config: [
      { key: 'siteId', title: 'Site ID', required: true },
      { key: 'apiKey', title: 'API key', secret: true, required: true },
    ],
    check: { path: '/campaigns', params: { limit: 1 } },
    resources: [
      { name: 'campaigns', path: '/campaigns', recordsPath: 'campaigns', primaryKey: 'id' },
      { name: 'customers', path: '/customers', recordsPath: 'results', primaryKey: 'id', cursorField: 'attributes.last_updated', filterClientSide: true, pagination: { type: 'cursor', cursorParam: 'start', cursorPath: 'next', limitParam: 'limit', pageSize: 1000 } },
      { name: 'newsletters', path: '/newsletters', recordsPath: 'newsletters', primaryKey: 'id' },
      { name: 'segments', path: '/segments', recordsPath: 'segments', primaryKey: 'id' },
      { name: 'broadcasts', path: '/broadcasts', recordsPath: 'broadcasts', primaryKey: 'id' },
      { name: 'transactional_messages', path: '/transactional', recordsPath: 'messages', primaryKey: 'id' },
    ],
  },

  {
    name: 'source-braze',
    displayName: 'Braze',
    description: 'Campaigns, canvases, segments, events and KPI data.',
    catalogSlug: 'braze', category: 'Applications', icon: 'braze',
    baseUrl: 'https://rest.{cluster}.braze.com',
    auth: { type: 'bearer' },
    config: [
      { key: 'cluster', title: 'REST endpoint cluster', required: true, help: 'e.g. iad-01, eu-01' },
      { key: 'apiKey', title: 'REST API key', secret: true, required: true },
    ],
    check: { path: '/campaigns/list', params: { page: 0 } },
    resources: [
      { name: 'campaigns', path: '/campaigns/list', params: { include_archived: true }, recordsPath: 'campaigns', primaryKey: 'id', cursorField: 'last_edited', filterClientSide: true, pagination: { type: 'page', pageParam: 'page', startAt: 0, pageSize: 100 } },
      { name: 'canvases', path: '/canvas/list', params: { include_archived: true }, recordsPath: 'canvases', primaryKey: 'id', cursorField: 'last_edited', filterClientSide: true, pagination: { type: 'page', pageParam: 'page', startAt: 0, pageSize: 100 } },
      { name: 'segments', path: '/segments/list', recordsPath: 'segments', primaryKey: 'id', pagination: { type: 'page', pageParam: 'page', startAt: 0, pageSize: 100 } },
      { name: 'events', path: '/events/list', recordsPath: 'events', primaryKey: 'name', pagination: { type: 'page', pageParam: 'page', startAt: 0, pageSize: 1000 } },
      { name: 'kpi_new_users', path: '/kpi/new_users/data_series', params: { length: 100 }, recordsPath: 'data', primaryKey: 'time' },
      { name: 'kpi_dau', path: '/kpi/dau/data_series', params: { length: 100 }, recordsPath: 'data', primaryKey: 'time' },
    ],
  },

  {
    name: 'source-iterable',
    displayName: 'Iterable',
    description: 'Lists, campaigns, templates, channels and experiments.',
    catalogSlug: 'iterable', category: 'Applications', icon: 'iterable',
    baseUrl: 'https://api.iterable.com/api',
    auth: { type: 'api_key', header: 'Api-Key' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/lists' },
    resources: [
      { name: 'lists', path: '/lists', recordsPath: 'lists', primaryKey: 'id' },
      { name: 'campaigns', path: '/campaigns', recordsPath: 'campaigns', primaryKey: 'id' },
      { name: 'channels', path: '/channels', recordsPath: 'channels', primaryKey: 'id' },
      { name: 'templates', path: '/templates', recordsPath: 'templates', primaryKey: 'templateId' },
      { name: 'experiments', path: '/experiments', recordsPath: 'experiments', primaryKey: 'experimentId' },
      { name: 'message_types', path: '/messageTypes', recordsPath: 'messageTypes', primaryKey: 'id' },
      { name: 'metadata', path: '/metadata', recordsPath: 'results', primaryKey: 'key' },
    ],
  },

  {
    name: 'source-brevo',
    displayName: 'Brevo',
    description: 'Contacts, lists, campaigns and transactional email stats.',
    catalogSlug: 'brevo', category: 'Applications', icon: 'brevo',
    baseUrl: 'https://api.brevo.com/v3',
    auth: { type: 'api_key', header: 'api-key' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/account' },
    resources: [
      { name: 'contacts', path: '/contacts', recordsPath: 'contacts', primaryKey: 'id', cursorField: 'modifiedAt', filterClientSide: true, pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 1000 } },
      { name: 'lists', path: '/contacts/lists', recordsPath: 'lists', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 50 } },
      { name: 'email_campaigns', path: '/emailCampaigns', recordsPath: 'campaigns', primaryKey: 'id', cursorField: 'modifiedAt', filterClientSide: true, pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'sms_campaigns', path: '/smsCampaigns', recordsPath: 'campaigns', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'senders', path: '/senders', recordsPath: 'senders', primaryKey: 'id' },
      { name: 'templates', path: '/smtp/templates', recordsPath: 'templates', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 50 } },
    ],
  },

  {
    name: 'source-activecampaign',
    displayName: 'ActiveCampaign',
    description: 'Contacts, lists, campaigns, automations and deals.',
    catalogSlug: 'activecampaign', category: 'Applications', icon: 'activecampaign',
    baseUrl: 'https://{account}.api-us1.com/api/3',
    auth: { type: 'api_key', header: 'Api-Token' },
    config: [
      { key: 'account', title: 'Account name', required: true, help: 'acme in acme.api-us1.com' },
      { key: 'apiKey', title: 'API key', secret: true, required: true },
    ],
    check: { path: '/users/me' },
    resources: [
      { name: 'contacts', path: '/contacts', recordsPath: 'contacts', primaryKey: 'id', cursorField: 'udate', filterClientSide: true, pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100, totalPath: 'meta.total' } },
      { name: 'lists', path: '/lists', recordsPath: 'lists', primaryKey: 'id' },
      { name: 'campaigns', path: '/campaigns', recordsPath: 'campaigns', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'automations', path: '/automations', recordsPath: 'automations', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'deals', path: '/deals', recordsPath: 'deals', primaryKey: 'id', cursorField: 'udate', filterClientSide: true, pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
      { name: 'tags', path: '/tags', recordsPath: 'tags', primaryKey: 'id', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'limit', pageSize: 100 } },
    ],
  },

  {
    name: 'source-campaign-monitor',
    displayName: 'Campaign Monitor',
    description: 'Clients, lists, subscribers, campaigns and templates.',
    catalogSlug: 'campaign-monitor', category: 'Applications', icon: 'campaignmonitor',
    baseUrl: 'https://api.createsend.com/api/v3.3',
    auth: { type: 'basic', username: '{apiKey}', password: 'x' },
    config: [{ key: 'apiKey', title: 'API key', secret: true, required: true }],
    check: { path: '/clients.json' },
    resources: [
      { name: 'clients', path: '/clients.json', recordsPath: null, primaryKey: 'ClientID' },
      { name: 'lists', path: '/clients/{parentId}/lists.json', recordsPath: null, primaryKey: 'ListID', child: { parent: 'clients', path: (p) => `/clients/${p.ClientID}/lists.json` } },
      { name: 'campaigns', path: '/clients/{parentId}/campaigns.json', recordsPath: null, primaryKey: 'CampaignID', child: { parent: 'clients', path: (p) => `/clients/${p.ClientID}/campaigns.json` } },
      { name: 'templates', path: '/clients/{parentId}/templates.json', recordsPath: null, primaryKey: 'TemplateID', child: { parent: 'clients', path: (p) => `/clients/${p.ClientID}/templates.json` } },
    ],
  },

  {
    name: 'source-postmark',
    displayName: 'Postmark',
    description: 'Servers, outbound messages, bounces, templates and stats.',
    catalogSlug: 'postmark', category: 'Applications', icon: 'postmark',
    baseUrl: 'https://api.postmarkapp.com',
    auth: { type: 'token_header', header: 'X-Postmark-Account-Token' },
    config: [{ key: 'apiKey', title: 'Account API token', secret: true, required: true }],
    check: { path: '/servers' },
    resources: [
      { name: 'servers', path: '/servers', recordsPath: 'Servers', primaryKey: 'ID' },
      { name: 'sender_signatures', path: '/senders', recordsPath: 'SenderSignatures', primaryKey: 'ID', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 500, totalPath: 'TotalCount' } },
      { name: 'templates', path: '/templates', recordsPath: 'Templates', primaryKey: 'TemplateId', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 100, totalPath: 'TotalCount' } },
      { name: 'bounces', path: '/bounces', recordsPath: 'Bounces', primaryKey: 'ID', pagination: { type: 'offset', offsetParam: 'offset', limitParam: 'count', pageSize: 500, totalPath: 'TotalCount' } },
    ],
  },
];
